/* ── TEMPLATES ── */
const TPLS = {
  blank:'',
  cornell:`<table style="border-collapse:collapse;width:100%;margin:12px 0;font-size:13.5px"><tbody><tr><td style="width:33%;border:1px solid var(--bor);padding:10px;vertical-align:top;background:var(--s2)"><strong>📌 Cues</strong><p style="min-height:160px;margin-top:6px" contenteditable="true">Key questions…</p></td><td style="border:1px solid var(--bor);padding:10px;vertical-align:top"><strong>📝 Notes</strong><p style="min-height:160px;margin-top:6px" contenteditable="true">Detailed notes…</p></td></tr><tr><td colspan="2" style="border:1px solid var(--bor);padding:10px;background:var(--s3)"><strong>📋 Summary</strong><p style="margin-top:6px" contenteditable="true">Summarise in your own words…</p></td></tr></tbody></table><p></p>`,
  outline:`<h2>📌 Topic</h2><h3>I. Main Idea</h3><ul><li>Sub-point A<ul><li>Detail</li></ul></li><li>Sub-point B</li></ul><h3>II. Main Idea</h3><ul><li>Sub-point A</li></ul><hr/><p><strong>Key Takeaway:</strong> </p>`,
  lab:`<h2>🔬 Lab Report</h2><h3>Purpose</h3><p>To investigate…</p><h3>Hypothesis</h3><p>If ___ then ___ because ___</p><h3>Materials</h3><ul><li>Item 1</li></ul><h3>Procedure</h3><ol><li>Step 1</li></ol><h3>Observations</h3><table style="border-collapse:collapse;width:100%;margin:9px 0"><thead><tr><th style="border:1px solid var(--bor);padding:7px;background:var(--s2)">Trial</th><th style="border:1px solid var(--bor);padding:7px;background:var(--s2)">Variable</th><th style="border:1px solid var(--bor);padding:7px;background:var(--s2)">Result</th></tr></thead><tbody><tr><td style="border:1px solid var(--bor);padding:7px" contenteditable="true">1</td><td style="border:1px solid var(--bor);padding:7px" contenteditable="true"></td><td style="border:1px solid var(--bor);padding:7px" contenteditable="true"></td></tr></tbody></table><h3>Conclusion</h3><p>In conclusion…</p>`,
  essay:`<h2>✍️ Essay Plan</h2><h3>Prompt</h3><blockquote style="border-left:4px solid var(--ac2);padding:8px 14px;background:var(--acll);border-radius:0 8px 8px 0">Paste question here…</blockquote><h3>Thesis</h3><p><strong>Argument:</strong> </p><h3>Body 1</h3><ul><li><strong>Topic sentence:</strong> </li><li><strong>Evidence:</strong> </li><li><strong>Analysis:</strong> </li></ul><h3>Body 2</h3><ul><li><strong>Topic sentence:</strong> </li><li><strong>Evidence:</strong> </li></ul><h3>Conclusion</h3><ul><li><strong>Restate thesis:</strong> </li></ul>`,
  vocab:`<h2>📖 Vocab List</h2><table style="border-collapse:collapse;width:100%;margin:12px 0;font-size:13px"><thead><tr><th style="border:1px solid var(--bor);padding:8px;background:var(--s2)">Term</th><th style="border:1px solid var(--bor);padding:8px;background:var(--s2)">Definition</th><th style="border:1px solid var(--bor);padding:8px;background:var(--s2)">Example</th></tr></thead><tbody>${Array(6).fill(0).map((_,i)=>`<tr ${i%2?'style="background:var(--s2)"':''}><td style="border:1px solid var(--bor);padding:8px" contenteditable="true"></td><td style="border:1px solid var(--bor);padding:8px" contenteditable="true"></td><td style="border:1px solid var(--bor);padding:8px" contenteditable="true"></td></tr>`).join('')}</tbody></table>`,
  review:`<h2>📚 Chapter Review</h2><h3>Chapter: </h3><h3>🔑 Key Concepts</h3><ul><li>Concept 1</li></ul><h3>📅 Key Dates / Names</h3><table style="border-collapse:collapse;width:100%;margin:8px 0;font-size:13px"><thead><tr><th style="border:1px solid var(--bor);padding:7px;background:var(--s2)">Date/Name</th><th style="border:1px solid var(--bor);padding:7px;background:var(--s2)">Significance</th></tr></thead><tbody><tr><td style="border:1px solid var(--bor);padding:7px" contenteditable="true"></td><td style="border:1px solid var(--bor);padding:7px" contenteditable="true"></td></tr></tbody></table><h3>❓ Exam Questions</h3><ol><li>Question 1?</li></ol>`,
  reading:`<h2>📰 Reading Notes</h2><table style="border-collapse:collapse;width:100%;margin:8px 0;font-size:13px"><tbody><tr><td style="border:1px solid var(--bor);padding:7px;background:var(--s2);font-weight:700;width:30%">Title</td><td style="border:1px solid var(--bor);padding:7px" contenteditable="true"></td></tr><tr><td style="border:1px solid var(--bor);padding:7px;background:var(--s2);font-weight:700">Author</td><td style="border:1px solid var(--bor);padding:7px" contenteditable="true"></td></tr></tbody></table><h3>Main Argument</h3><p>The author argues that…</p><h3>Key Points</h3><ul><li>Point 1</li></ul><h3>My Analysis</h3><p>I think…</p>`,
  meeting:`<h2>🤝 Study Group</h2><p><strong>Date:</strong> ___ | <strong>Members:</strong> ___</p><h3>Agenda</h3><ol><li>Item 1</li></ol><h3>Discussion Notes</h3><p></p><h3>Action Items</h3><table style="border-collapse:collapse;width:100%;margin:8px 0;font-size:13px"><thead><tr><th style="border:1px solid var(--bor);padding:7px;background:var(--s2)">Task</th><th style="border:1px solid var(--bor);padding:7px;background:var(--s2)">Owner</th><th style="border:1px solid var(--bor);padding:7px;background:var(--s2)">Due</th></tr></thead><tbody><tr><td style="border:1px solid var(--bor);padding:7px" contenteditable="true"></td><td style="border:1px solid var(--bor);padding:7px" contenteditable="true"></td><td style="border:1px solid var(--bor);padding:7px" contenteditable="true"></td></tr></tbody></table>`,
  mindmap:`<h2>🧠 Mind Map</h2><div style="background:var(--acl);border-radius:10px;padding:11px 16px;margin:10px 0;text-align:center;font-weight:700;font-size:15px;color:var(--ac)" contenteditable="true">Central Idea</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px"><div style="background:#DBEAFE;border-radius:8px;padding:10px"><strong style="color:#1E40AF">Branch 1</strong><ul style="margin-top:6px;padding-left:14px" contenteditable="true"><li>Sub-point</li></ul></div><div style="background:#FCE7F3;border-radius:8px;padding:10px"><strong style="color:#9D174D">Branch 2</strong><ul style="margin-top:6px;padding-left:14px" contenteditable="true"><li>Sub-point</li></ul></div><div style="background:#D1FAE5;border-radius:8px;padding:10px"><strong style="color:#065F46">Branch 3</strong><ul style="margin-top:6px;padding-left:14px" contenteditable="true"><li>Sub-point</li></ul></div><div style="background:#EDE9FE;border-radius:8px;padding:10px"><strong style="color:#4C1D95">Branch 4</strong><ul style="margin-top:6px;padding-left:14px" contenteditable="true"><li>Sub-point</li></ul></div></div>`,
  timeline:`<h2>📅 Timeline</h2><table style="border-collapse:collapse;width:100%;margin:12px 0;font-size:13px"><thead><tr><th style="border:1px solid var(--bor);padding:8px;background:var(--s2);width:25%">Date</th><th style="border:1px solid var(--bor);padding:8px;background:var(--s2)">Event</th><th style="border:1px solid var(--bor);padding:8px;background:var(--s2)">Significance</th></tr></thead><tbody>${Array(5).fill(0).map((_,i)=>`<tr ${i%2?'style="background:var(--s2)"':''}><td style="border:1px solid var(--bor);padding:8px" contenteditable="true"></td><td style="border:1px solid var(--bor);padding:8px" contenteditable="true"></td><td style="border:1px solid var(--bor);padding:8px" contenteditable="true"></td></tr>`).join('')}</tbody></table>`,
  problem:`<h2>🔢 Problem Set</h2><p><strong>Topic:</strong> ___ | <strong>Chapter:</strong> ___</p><h3>Key Formulas</h3><div style="background:var(--s3);border-radius:8px;padding:10px 13px;font-family:var(--font-m);font-size:12.5px" contenteditable="true">f(x) = ...</div><h3>Problems</h3><ol><li><p><strong>Problem:</strong> </p><p><strong>Solution:</strong> </p></li></ol>`,
  research:`<h2>🧪 Research Notes</h2><table style="border-collapse:collapse;width:100%;margin:8px 0;font-size:13px"><tbody><tr><td style="border:1px solid var(--bor);padding:7px;background:var(--s2);font-weight:700;width:30%">Research Question</td><td style="border:1px solid var(--bor);padding:7px" contenteditable="true"></td></tr><tr><td style="border:1px solid var(--bor);padding:7px;background:var(--s2);font-weight:700">Source</td><td style="border:1px solid var(--bor);padding:7px" contenteditable="true"></td></tr></tbody></table><h3>Background</h3><p></p><h3>Findings</h3><ul><li>Finding 1</li></ul><h3>Conclusion</h3><p></p><h3>Sources / Citations</h3><ol><li></li></ol>`,
  formula:`<h2>📐 Formula Reference Sheet</h2><p><strong>Subject:</strong> ___ | <strong>Unit:</strong> ___</p>${['Algebra','Geometry','Trigonometry','Calculus'].map(cat=>`<h3>${cat}</h3><table style="border-collapse:collapse;width:100%;margin:6px 0;font-size:12.5px"><thead><tr><th style="border:1px solid var(--bor);padding:7px;background:var(--s2);width:40%">Formula</th><th style="border:1px solid var(--bor);padding:7px;background:var(--s2)">Description</th><th style="border:1px solid var(--bor);padding:7px;background:var(--s2)">Variables</th></tr></thead><tbody><tr><td style="border:1px solid var(--bor);padding:7px;font-family:var(--font-m)" contenteditable="true"></td><td style="border:1px solid var(--bor);padding:7px" contenteditable="true"></td><td style="border:1px solid var(--bor);padding:7px" contenteditable="true"></td></tr></tbody></table>`).join('')}`,
  debate:`<h2>⚖️ Debate Notes</h2><p><strong>Topic:</strong> ___</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:12px 0"><div style="background:#D1FAE5;border-radius:8px;padding:12px"><h3 style="color:#065F46">✅ For (Arguments)</h3><ol><li contenteditable="true">Argument 1</li><li contenteditable="true">Argument 2</li></ol></div><div style="background:#FEE2E2;border-radius:8px;padding:12px"><h3 style="color:#991B1B">❌ Against (Counterarguments)</h3><ol><li contenteditable="true">Counterargument 1</li><li contenteditable="true">Counterargument 2</li></ol></div></div><h3>Evidence</h3><ul><li>Source 1: </li></ul><h3>My Position / Verdict</h3><p></p>`,
  book:`<h2>📘 Book Report</h2><table style="border-collapse:collapse;width:100%;margin:8px 0;font-size:13px"><tbody><tr><td style="border:1px solid var(--bor);padding:7px;background:var(--s2);font-weight:700;width:25%">Title</td><td style="border:1px solid var(--bor);padding:7px" contenteditable="true"></td></tr><tr><td style="border:1px solid var(--bor);padding:7px;background:var(--s2);font-weight:700">Author</td><td style="border:1px solid var(--bor);padding:7px" contenteditable="true"></td></tr><tr><td style="border:1px solid var(--bor);padding:7px;background:var(--s2);font-weight:700">Genre</td><td style="border:1px solid var(--bor);padding:7px" contenteditable="true"></td></tr><tr><td style="border:1px solid var(--bor);padding:7px;background:var(--s2);font-weight:700">Setting</td><td style="border:1px solid var(--bor);padding:7px" contenteditable="true"></td></tr></tbody></table><h3>Plot Summary</h3><p></p><h3>Main Characters</h3><ul><li><strong>Character:</strong> Description</li></ul><h3>Themes</h3><ul><li>Theme 1</li></ul><h3>My Opinion</h3><p></p><h3>Favourite Quote</h3><blockquote contenteditable="true">"..."</blockquote>`
};
function applyTpl(key){
  const html=TPLS[key]; if(html===undefined) return;
  if(!noteId){newNote();setTimeout(()=>applyTpl(key),100);return;}
  g('doc-ed').innerHTML=html||''; touch();
}

